services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash -c "python manage.py migrate --run-syncdb && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app  # Maps the entire Django project, including the SQLite file
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: arm32v7/redis:6.0
    ports:
      - "6379:6379"


  celery:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A deals_bot worker -l info
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A deals_bot beat -l info
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app

